version: '2'

services:

#  publb:
#    image: dockercloud/haproxy:1.6.7
#    ports:
#    - "80:80"
#    - "443:443"
#    - "1936:1936"
#    links:
#    - portal
#    - kong
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#    - "STATS_AUTH=stats:stats"
#    - "STATS_PORT=1936"
#    restart: unless-stopped

  kong-database:
    image: postgres:9.6
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_PASSWORD=kong"
    restart: unless-stopped

  kong:
    image: haufelexware/wicked.kong:latest
    depends_on:
      - "kong-database"
    security_opt:
      - seccomp:unconfined
    expose:
      - "8000"
      - "8001"
    environment:
      - "DATABASE=postgres"
      # - "VIRTUAL_HOST=api.portal.local"
      # - "VIRTUAL_HOST_WEIGHT=100"
      # - "EXCLUDE_PORTS=7946,8001,8443"
      # - "EXTRA_SETTINGS=http-request set-header X-Forwarded-Port %[dst_port]"
      # - "SSL_CERT=${GATEWAY_PEM}"
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
      # - "443:443"
      # - "1936:1936"

  portal-api:
    image: haufelexware/wicked.portal-api:latest
    environment:
      - "NODE_ENV=development"
      - "PORTAL_CONFIG_KEY=2c94d4ffce4b631a776289dca18bc9afec60f667"
      - "GIT_REPO=https://github.com/OpenDataStack/wicked-config.git"
      - "GIT_CREDENTIALS=angrycactus-bot"
    restart: unless-stopped

  portal:
    image: haufelexware/wicked.portal:latest
    depends_on:
      - "portal-api"
      - "kong"
    expose:
      - "3000"
    # environment:
    # - "PORTAL_NETWORK_APIHOST=localhost:3000"
#    - "VIRTUAL_HOST=portal.local"
#    - "VIRTUAL_HOST_WEIGHT=0"
#    - "SSL_CERT=${PORTAL_PEM}"
    restart: unless-stopped
    ports:
      - "3000:3000"

  portal-kong-adapter:
    image: haufelexware/wicked.portal-kong-adapter:latest
    depends_on:
      - "portal-api"
      - "kong"
    environment:
      - "PORTAL_CONFIG_KEY=2c94d4ffce4b631a776289dca18bc9afec60f667"
    restart: unless-stopped

  portal-mailer:
    image: haufelexware/wicked.portal-mailer:latest
    restart: unless-stopped
    depends_on:
      - "portal-api"
