version: '2'

services:

  publb:
    image: dockercloud/haproxy:1.6.7
    ports:
    - "443:443"
    - "1936:1936"
    links:
    - portal
    - kong
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - "STATS_AUTH=stats:stats"
    - "STATS_PORT=1936"
    restart: unless-stopped

  kong-database:
    image: postgres:9.6
    volumes:
    - "/var/lib/postgresql/data"
    environment:
    - "POSTGRES_USER=kong"
    - "POSTGRES_PASSWORD=kong"
    restart: unless-stopped

  kong:
    image: haufelexware/wicked.kong:latest
    depends_on:
    - "kong-database"
    security_opt:
    - seccomp:unconfined
    expose:
    - "8000"
    environment:
    - "DATABASE=postgres"
    - "VIRTUAL_HOST=https://api.portal.local:443"
    - "VIRTUAL_HOST_WEIGHT=100"
    - "EXCLUDE_PORTS=7946,8001,8443"
    - "EXTRA_SETTINGS=http-request set-header X-Forwarded-Port %[dst_port]"
    - "SSL_CERT=${GATEWAY_PEM}"
    restart: unless-stopped

  portal-api:
    image: haufelexware/wicked.portal-api:latest
    environment:
    - "NODE_ENV=default"
    - "PORTAL_CONFIG_KEY=2c94d4ffce4b631a776289dca18bc9afec60f667"
    - "PORTAL_NETWORK_APIHOST=portal.local"
    - "GIT_REPO=https://github.com/OpenDataStack/wicked-config.git"
    - "GIT_CREDENTIALS=angrycactus-bot:A-1redwarrior+"
    - "GIT_BRANCH=master"
    restart: unless-stopped

  portal:
    image: haufelexware/wicked.portal:latest
    depends_on:
    - "portal-api"
    expose:
    - "3000"
    environment:
    - "VIRTUAL_HOST=https://portal.local:443"
    - "VIRTUAL_HOST_WEIGHT=0"
    - "SSL_CERT=${PORTAL_PEM}"
    restart: unless-stopped

  portal-kong-adapter:
    image: haufelexware/wicked.portal-kong-adapter:latest
    depends_on:
    - "portal-api"
    restart: unless-stopped

  portal-mailer:
    image: haufelexware/wicked.portal-mailer:latest
    restart: unless-stopped
    depends_on:
    - "portal-api"

  portal-chatbot:
    image: haufelexware/wicked.portal-chatbot:latest
    restart: unless-stopped
    depends_on:
    - "portal-api"
